### ISSUE TITLE
Better folder/directory naming for non-coder

### ISSUE THREAD

**Issue by agusmu** [wp-e-commerce/wpec-theme-engine-v2#18]
This morning Dan told me to check this repo. Okay, I think it is good direction for WPEC to create new and better theme engine...

I do not check Wiki first to act as a newbie... I tried to find the main template files... Then, first I check "templates" folder, and then I realize it is not there... I skip mvc folder because I really have no idea what is mvc :) then I am lost...

So, yes, the directory name is confuse me, totally... I hope you can follow others wordpress ecommerce plugin direction for template hierarchy... Put everything that can be overwrited on wordpress theme in one folder, for example "themes" or "templates"... Do not use "mvc", "controllers" name...

I believe that this wpec theme engine is build for everyone, not only for coder...

Cheers,
Agus

**Comment by garyc40** [comment]
Great suggestion!

We'll soon have a user interface that helps you visually migrate / override default templates.

In the mean time, I've made changes so that everything that can be customized and overridden are now located under "theming" folder  :)

New folder structure would look like this:
https://github.com/wp-e-commerce/wpec-theme-engine-v2/tree/pr-18

Does it look good enough? :)

**Comment by agusmu** [comment]
Hi @garyc40 it is a really good start. That is what I mean. You are fantastic...

The next step will be standarizing the filename of some template-parts to be more wordpress standard... I hope I can spend some times to make an example for you on this week.

**Comment by garyc40** [comment]
That would be really helpful. Thank you so much @agusmu.

We made this template engine public even when it is still in its very rough state so that we can gradually mold it into something that both users and theme developers will enjoy using and customizing. So any feedback from our community is greatly appreciated.
